### ISSUE TITLE
useEffect with authState dependency that dispatches to Redux triggers constantly

### ISSUE THREAD

**Issue by aarestad** [okta/okta-react#139]
## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Trying to use `authState` as a dependency for `useEffect` which dispatches a Redux action causes constant firing of the effect on every tick, even if auth state has not changed. This worked fine with okta-react v3, but with v6, it appears to have regressed. I am able to get around this by using `authState?.isAuthenticated` as the dependency instead, but the documented example in the README indicate that this should not be required.

## Expected behavior

The `useEffect` should only fire when authState has actually changed, i.e. a login state change has occurred

## Minimal reproduction of the problem with instructions

```
  useEffect(() => {
    console.log('authState change?');

    if (authState?.accessToken) {
      dispatch(doAReduxDispatch(authState.accessToken); // the Redux state handler does not touch authState or affect the login state
    }
  }, [authState]);
```

## Environment

- Package version: v6.0
- React version: 17.0.1
- Browser: Chrome
- OS: MacOS 11
- Node version (`node -v`): v12.21
- Other:

## Configuration

- Okta application type: OIDC

**Comment by shuowu** [comment]
@aarestad With v6 each authState update creates a new `authState` object, that's why useEffect will be triggered when an update authState event happens. But the `isAuthenticated` states may not be changed in that case.

For your use case, I would suggest to watch on `authState?.accessToken.accessToken`, as the accessToken can be renewed  if you are using the [active auto renew](https://github.com/okta/okta-auth-js#running-as-a-service) token service.

Also, looks like the logic in your hook is to store accessToken to the redux store, but as the tokens are kept and properly updated with the SDK's internal logic, you can try the [useOktaAuth](https://github.com/okta/okta-react#useoktaauth) hook to get access to the latest authState which includes tokens.

**Comment by aarestad** [comment]
Good point about the token - rest assured I am not storing it in the Redux store. :) In any case, you should probably update your README examples since they all use `authState` as the only dependency. Thank you!

**Comment by shuowu** [comment]
Looks like [this example](https://github.com/okta/okta-react#use-the-access-token-function-based) is the only one in readme with `useEffect` hook, but looks like the logic is protected with `if(authState.isAuthenticated)` which actually make sense, as it can make the initial request (only once) and also keep watching on tokens change.

**Comment by aarestad** [comment]
The issue i was seeing was that it was firing over and over though, not just once. Also, I noticed it was only happening when I was making a Redux dispatch call in my `useEffect` handler - when I removed that, using `authState` itself as the dependency worked fine, and e.g. a console log only triggered once auth state changed. My Redux handler was itself making a service call, so it would make tens of service calls per second.

**Comment by shuowu-okta** [comment]
Is your component wrapped inside another component that may affect by the casading states change that caused by the dispatch function?

**Comment by aarestad** [comment]
Our react-redux <Provider> is on the top level of our app. That might be the problem here. 🤔

**Comment by aarestad** [comment]
Yeah, moving the `<Provider>` inside the `<Security>` component did the trick. Thank you!
