### ISSUE TITLE
Upgrading react-router v7

### ISSUE THREAD

**Issue by ksankumar** [okta/okta-react#288]
### Describe the bug

I am getting the below error when i upgrade my react-router version 7.0.x

```
 node_modules/@okta/okta-react/bundles/okta-react.esm.js:21:32:
 import * as ReactRouterDom from 'react-router-dom'
```

### Reproduction Steps?

Just upgrade the react-route version in package.json

  ```
 "@okta/okta-auth-js": "^7.9.0",
 "@okta/okta-react": "^6.9.0",
 "react-router": "^7.0.2",
```

### SDK Versions

System:
OS: Windows 10 10.0.19045
CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
Memory: 42.44 GB / 63.64 GB
Binaries:
Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
Yarn: 4.5.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
Watchman: 20240310.093207.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
Browsers:
Chrome: ETM.ico
Edge: Chromium (127.0.2651.74)
Internet Explorer: 11.0.19041.4355
npmPackages:
@okta/okta-auth-js: ^7.9.0 => 7.9.0
@okta/okta-react: ^6.9.0 => 6.9.0
react: ^19.0.0 => 19.0.0
react-dom: ^19.0.0 => 19.0.0
react-router: ^7.0.2 => 7.0.2

**Comment by jaredperreault-okta** [comment]
`react-router-dom` is a [peer dependency](https://github.com/okta/okta-react/blob/master/package.json#L57) of this library. We have a backlog item to improve our integration with `react-router` however it hasn't been prioritized yet.

It seems like `react-router` no longer requires a separate `react-router-dom` package as of v7, which is why you're getting this error. If you include `react-router-dom` in your `package.json` it should unblock you
