### ISSUE TITLE
unable to capture session expiration and need help with refreshing tokens silently with react SPA

### ISSUE THREAD

**Issue by pbollaram** [okta/okta-react#45]
Hi,

i was trying to capture Okta session expiration and unable to find any good documentation.
please help me with following questions.
1. Your documentation mention that onSessionExpired (deprecated). if that so how do i capture the moment when okta session expires ? and if there is a method available then is calling ‘/v1/authorize?prompt=none’ from that method would refresh token silently?
2. in another case the Okta token was expired and only idToken was present in local storage. this is not preventing me access components that were wrapped with SecureRoute. is it because having either one of idToken or accessToken is enough to consider a successful login ?
3. i am using Security onAuthRequired={onAuthRequired} />. i thought if session expires then onAuthRequired method will be called but this is not the case. is my understanding correct or am i missing something here.

below is my configuaration
const config = {
issuer: process.env.REACT_APP_OKTA_ORG_URL,
redirect_uri: ${window.location.origin}/implicit/callback,
client_id: process.env.REACT_APP_OKTA_CLIENT_ID,
scope: [‘openid’, ‘profile’, ‘email’, ‘groups’],
pkce: true,
cookies: {
secure: window.location.protocol === ‘https:’,
},
tokenManager:{
       autoRenew: true,
      secure: true,
      storage: 'localStorage',
}
}

<Security {...config}> <App /> </Security>

Please help me with correct configuration if you think above wrong.

**Comment by swiftone** [comment]
Hi @pbollaram - Let's see if I can answer some of your questions:

> how do i capture the moment when okta session expires

Your config mentions `autoRenew: true`, so in general you don't need to check for expiration - tokens will automatically be replaced until they cannot (for example, session on the issuer site expires, or 3rd party cookies are blocked) and when they cannot the user will be prompted to login again before they can access routes that use `<SecureRoute>`.  Do you have a particular need to capture this moment?

Notably, if a token is DUE to expire, autoRenew will try to to replace the token with a fresh one, meaning that the token never actually expires until the autoRenew fails.

> if there is a method available then is calling ‘/v1/authorize?prompt=none’ 

`autoRenew: true` will do this for you, silently (note: if 3rd party cookies are blocked, such as from recent Safari by default, this silent token replacement will fail)

> is it because having either one of idToken or accessToken is enough to consider a successful login?

Yes.  If you want to be sure that both tokens exist, you can override the behavior with something like:
```
const authService = new AuthService({
  // ...other configs
  isAuthenticated: async () => {
    const idToken = await authService.getTokenManager().get('idToken');
    const accessToken = await authService.getTokenManager().get('accessToken');
    return !!(idToken && accessToken);
  }
});
<Security authService={authService} />
```

Please note that requiring both tokens to be considered authenticated will become the default in the next major version of this library, so when that happens you will need to update your code accordingly (and be able to remove an override like this)

>  if session expires then onAuthRequired method will be called 

Almost.  `onAuthRequired` is called when authService.login() is called, and that is called by `<SecureRoute>` - If the user is not viewing a route that is in `<SecureRoute>`, then this chain does not kick off until they are (or until you otherwise call authService.login())

**Comment by pbollaram** [comment]
Thank you so much for the detailed explanation. Yes my app need to log some info when the token expires and how do i capture that ? coming to auto renew which works fine and i do not have any issues with it.

Please note that requiring both tokens to be considered authenticated will become the default in the next major version of this library, so when that happens you will need to update your code accordingly (and be able to remove an override like this) - thank you for the heads up.

**Comment by swiftone** [comment]
To know when things happen with the tokens, you have a few options.

You can set a callback to react to events about changing authstate:
https://github.com/okta/okta-react#authserviceoneventname-callback

However, that won't give you a lot of information about WHY the tokens are changing out.  If you need more detailed information, you can get the tokenManager from the internal instance of okta-auth-js.

https://github.com/okta/okta-react#authservicegettokenmanager

With the tokenManager, you can subscribe to events, such as 'expired', that fire when tokens change.  I don't recommend using these events to drive changes to your app, but for logging events it should be just what you are looking for:
https://github.com/okta/okta-auth-js/blob/master/README.md#tokenmanageronevent-callback-context

**Comment by pbollaram** [comment]
Thank you. this is helpful.
