### ISSUE TITLE
Unhandled Rejections and simulating errors

### ISSUE THREAD

**Issue by tomspeak** [okta/okta-react#76]
I am upgrading to 4.1.0 from 3.8.0 and am having a few issues.

I am trying to test that #25 was properly fixed, which it does not seem to, below is using `console.log(authState)`

```
{isPending: true, isAuthenticated: false, idToken: null, accessToken: null, refreshToken: null} 

{isPending: true, isAuthenticated: false, idToken: null, accessToken: null, refreshToken: null}

{accessToken: undefined, idToken: undefined, refreshToken: undefined, isPending: false, isAuthenticated: false}
```

As you can see, there's no reasonable way for my UI to handle this state. It's: pending, not authenticated and has no errors? 

`authState.error` is never populated. In `3.8.0` I was able to add an invalid entry to `scopes`, and it would reliably cause an error, and populate it in `authState.error`.

Now, when I do this (via the new `oktaAuth` API config, I get this:

```
Unhandled Rejection (OAuthError): One or more scopes are not configured for the authorization server resource.

[REDACTED]/OktaAuth/lib/token.ts:195
  192 |     });
  193 | }
  194 | function validateResponse(res, oauthParams) {
> 195 |     if (res['error'] || res['error_description']) {
  196 |         throw new OAuthError(res['error'], res['error_description']);
  197 |     }
  198 |     if (res.state !== oauthParams.state) {

[REDACTED]/OktaAuth/lib/token.ts:223
  220 | // Handling the result from implicit flow or PKCE token exchange
  221 | return Promise.resolve()
  222 |     .then(function () {
> 223 |     validateResponse(res, tokenParams);
      | ^  224 | }).then(function () {
  225 |     var tokenDict = {};
  226 |     var expiresIn = res.expires_in;
```

Please note that I understand this is *supposed* to error, it's how the error is unhandled, thrown and crashes my app, versus the old behaviour of populating `authState.error`.

1. How do I deterministically throw an okta error that will result in `authState.error` being populated?
2. Why is there an unhandled rejection being thrown? It currently takes down my whole app, I have functionality to handle rendering `authState.error`, and this avoids it.

**Comment by swiftone** [comment]
@tomspeak - Thanks for your report.  Let's see if we can find some answers.

First, I want to clarify something that does not directly impact your issue, but could matter for anyone else reading this ticket, and could impact you outside of this specific issue:

Pending does NOT mean "the app is talking to Okta".  Pending means "the app is waiting on any async process to figure out if the user is authenticated."  That could be talking to Okta, but more commonly it means waiting on browser storage to see if we have stored tokens (while cookies and localstorage are synchronous, there are also asynchronous methods of token storage, so there is a period of "I don't know yet if we're authenticated" even without any external calls).  That is what "Pending" means here.  So it's perfectly normal to stop being pending and not be authenticated and have no error.  

In the case you describe here, of course, there _is_ an error situation, I'm just clearing up that your app should not expect that when pending is done you must get either an authenticated state or an error. When pending is done, you should expect to know if the user is authenticated or not.  That's all the end of pending tells you.

Okay, that established, let's move on to your error.  

Your expectation seems correct to me, and we'll dig into it.  However, as another general note, you should always trap errors from calling login code. The team has been working on how to manage reporting errors, because the main trick is that async processes (such as login) can have errors that you may want to handle outside of the rendering cycle.

I'll file an internal ticket so we can dig into it, but in the meantime, can you share some details about how you are trigging a login for an unauthenticated user?   That will help us recreate the case an examine the best solution.

**Comment by tomspeak** [comment]
hey @swiftone — thanks for the background on `pending`, I wonder if there's a better name? I know I made a lot of assumptions based off the name.

I am using a react function component, and this is my `useEffect` handler:

```typescript
  useEffect(() => {
    if (
      !authState.isAuthenticated &&
      !authState.isPending &&
      !authState.error
    ) {
      (async function signIn() {
        try {
          console.log("signing in"); // called once
          await oktaAuth.signInWithRedirect();
        } catch (e) {
          console.log("okta error: ", e); // never called
        }
      })();
    }
  }, [authState, oktaAuth]);
```

That console log is never called, and then my app crashes with the aforementioned error. I am redirected to `/login/callback?state=[REDACTED]&error=invalid_scope&error_description=One+or+more+scopes+are+not+configured+for+the+authorization+server+resource`, but then further redirected to just `/login/callback`, where my app implodes with the error I posted above.

It's a very basic set up, with minimal configuration:

```typescript
const authService = new OktaAuth({
  issuer,
  clientId,
  redirectUri: window.location.origin + loginCallbackUrl,
  tokenManager: {
    autoRenew: true,
  },
  scopes: ["openid", "email", "throw-an-error"],
});
```

Please let me know if you need more information. I just have to be mindful of what I share, if you need more details, could we move this to a private channel?

Thanks a lot!

**Comment by swiftone** [comment]
Internal ref: OKTA-361608

**Comment by tomspeak** [comment]
hey, i was wondering if there was a rough ETA on when this is likely to be resolved? 

days, weeks? just trying to plan whether to keep this upgrade around or will we have to move it back weeks. cheers!

**Comment by shuowu** [comment]
@tomspeak Thanks for the follow-up! The internal ticket has not been prioritized yet, no ETA by now.

**Comment by tomspeak** [comment]
Hey, just wanted to follow up on this. We're still stuck on v3 because of this issue. Cheers!

**Comment by aarongranick-okta** [comment]
@tomspeak I'm sorry that this issue is still troubling you. The error in this case will occur on the callback. It will not be thrown from `showSignInAndRedirect` (because the browser will redirect and then return). The `LoginCallback` component in the react SDK has a known issue where it will not display the error on the screen, however you can workaround this by using your own callback component. We recommend this because the default component has no default error handling except to display it to the user. Likely, you would want to direct the user to perform some action based upon the type of error. 
The error, in the given case, will be thrown from `handleLoginRedirect`: https://github.com/okta/okta-react/blob/master/src/LoginCallback.tsx#L26

**Comment by aarongranick-okta** [comment]
@tomspeak We have released a fix for this issue. After upgrading to `@okta/okta-react` [version 5.1.1](https://github.com/okta/okta-react/releases/tag/okta-react-5.1.1) you should see OAuth callback errors caught and displayed in the `LoginCallback` component. Please let us know if this has resolved your issue, or if you are still seeing a problem.

**Comment by shuowu** [comment]
Close the issue for now. @tomspeak Feel free to reopen the issue if you are still seeing issue with v5.1.1.
